### ISSUE TITLE
Should I concatenate a general dictionary with my domain-specific dictionary?

### ISSUE THREAD

**Issue by sinablk** [tca19/dict2vec#3]
I have a domain-specific corpus of geological documents with most of the vocabulary and the associated dictionary focused on geology and geochemistry. So the strong/weak pairs I generate are small (obviously) and very specific to geology.

I was wondering if any experiments were carried out (or thoughts you might have) in learning word embeddings using domain-specific lexical dictionaries. The task that I have is unsupervised, so its harder for me to know if concatenating my domain-specific strong/weak pairs with a general English dictionary (Merriam-Webster, Cambrdige, etc.) gives more accurate results than only using my own smaller domain-specific dictionary.

Would you recommend concatenating my dictionary with a general English dictionary for learning word embeddings, or just using my standalone domain-specific dictionary is good enough?

Thank you for the great work!

**Comment by tca19** [comment]
Hello sinablk,

Thank you for your interest in dict2vec software. We have not carried out any experiments to learn word embeddings with domain-specific lexical dictionaries. However, we have tested a similar idea. Instead of training word embeddings with the classical methods, which consist in using a large general text corpus like Wikipedia and an external source of knowledge like strong/weak pairs, we trained word embeddings with the downloaded definitions from the Web as the text corpus and the generated strong/weak pairs as positive sampling (Wikipedia is therefore not used in this experiment, only the word definitions are used as a text corpus). Although the size of the word definitions corpus is much smaller than Wikipedia (5M tokens for the definition corpus, 4B for Wikipedia), word vectors learned with this experiment exhibit scores in semantic similarity tasks much higher than the ones reported in the paper (0.640 for the weighted average on all the datasets while the best score reported in the paper is 0.599). My intuition on this behavior: using a small but very specific corpus is much better when one wants word embeddings dedicated to a specific task (in the case of the semantic similarity task, we want word vectors that reflect the semantic properties of words, so using only the definitions makes sense).

For your question, I suggest you to train word embeddings with your corpus of geological documents and the geology/geochemistry dictionaries (so without using Wikipedia and general English dictionaries at all). Then, based on the scores you get on your evaluation task, if the results are not good enough or if you are missing a lot of words that do not appear in your corpus, you can for example initiate the values of vectors in the dict2vec software with pre-trained vectors like the ones from fasttext or GloVe instead of using a random initialization and then train them with your specific corpus and dictionaries. In that way, the learned vectors would encode linguistic information from the pre-trained values, but also the information about geology/geochemistry from your corpus/dictionaries.

**Comment by sinablk** [comment]
Thank you for the detailed response! It was very helpful. Initiating the vectors with some pre-trained ones was something I hadn't thought of. Will definitely see about a way of doing that. Thanks!
